# Generated by Django 5.0.6 on 2024-07-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_alter_auction_current_bid_alter_auction_starting_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_price',
            field=models.IntegerField(),
        ),
    ]
