# Generated by Django 5.0.6 on 2024-07-18 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_alter_auction_current_bid_alter_auction_starting_bid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisorslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('saturday', 'Saturday'), ('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thrusday', 'Thrusday'), ('friday', 'Friday')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('message', models.TextField(blank=True, null=True)),
                ('max_user', models.IntegerField(default=10)),
                ('total_user', models.IntegerField(blank=True, default=0, null=True)),
                ('meet_link', models.CharField(blank=True, max_length=250, null=True)),
                ('booked_user_list', models.ManyToManyField(blank=True, related_name='booked_User', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
