# Generated by Django 5.0.6 on 2024-07-27 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_advisorslot'),
        ('Dashboard', '0003_alter_bid_bid_price'),
    ]

    operations = [
    ]
