# Generated by Django 5.0.6 on 2024-07-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_merge_0003_advisorslot_0003_alter_bid_bid_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='house_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
