# Generated by Django 4.2.13 on 2024-07-28 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Dashboard', '0008_auction_latitude_auction_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='longitude',
        ),
        migrations.CreateModel(
            name='Buyer_Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
