# Generated by Django 5.0.6 on 2024-07-30 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0012_alter_auction_creation_date'),
        ('User', '0005_remove_profile_ratings_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_seller', to='User.seller'),
        ),
        migrations.DeleteModel(
            name='Buyer_Seller',
        ),
    ]
