# Generated by Django 4.2.13 on 2024-08-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0014_paperworkconfirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='papers_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='PaperworkConfirmation',
        ),
    ]
