# Generated by Django 4.2.13 on 2024-08-01 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0015_auction_papers_confirmed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousePaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='house_papers/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.auction')),
            ],
        ),
    ]
