# Generated by Django 4.2.13 on 2024-08-02 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0016_housepaper'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HousePaper',
        ),
    ]
