# Generated by Django 4.2.13 on 2024-08-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0018_housepaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='purchase_success',
            field=models.BooleanField(default=False),
        ),
    ]
