# Generated by Django 4.2.13 on 2024-08-07 16:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0019_auction_purchase_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
