# Generated by Django 5.0.6 on 2024-07-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
