# Generated by Django 5.0.6 on 2024-07-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_profile_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
